webui-dev/webui

include/webui/webui.hpp
src/webui.cpp

fixed creating profile with firefox.app, and shell quoting in general

some fixes , primarly targetting macos

---

README.md

* Short Link Preview on Supported Languages Table
* Add V Link to Examples List

Short Link Preview & Add V Link to Examples

---

examples/C/call_c_from_js/main.c
examples/C/serve_folder/Windows/MSVC/index.html
examples/C/serve_folder/main.c
examples/TypeScript/Deno/webui_server/example.c
examples/TypeScript/Nodejs/webui_server/example.c
include/webui.h
src/webui.c

* Adding the possibility of calling C from JS and waiting for the response

Call C from JS with a response

---

.gitignore
build.zig
examples/Zig/call_from_js/build.zig
examples/Zig/call_from_js/build.zig.zon
examples/Zig/call_from_js/src/c.zig
examples/Zig/call_from_js/src/main.zig
examples/Zig/hello_world/build.zig
examples/Zig/hello_world/build.zig.zon
examples/Zig/hello_world/src/c.zig
examples/Zig/hello_world/src/main.zig
examples/Zig/minimal/build.zig
examples/Zig/minimal/build.zig.zon
examples/Zig/minimal/c.zig
examples/Zig/minimal/minimal.zig
examples/Zig/serve_folder/build.zig
examples/Zig/serve_folder/build.zig.zon
examples/Zig/serve_folder/index.html
examples/Zig/serve_folder/second.html
examples/Zig/serve_folder/src/c.zig
examples/Zig/serve_folder/src/main.zig

I've ported the C examples to Zig and wrote a `build.zig` to allow zig code to depend directly on webui (see examples). The URLs in the zig example code's `build.zig.zon` should be updated to point at the main repository but we have to know a commit hash with the `build.zig` available before that can be done.

Add zig build system

---

README.md
src/webui.c

Add Chromium support

---

src/webui.c

Sorry for not testing before. I compiled this patch and it is working nicely
Sorry, im not familiar with C

Fix Chromium Path

---

README.md

Adding the `Contributions` section in the readme file.

Adding the contributions section

---

build/MacOS/Clang/Makefile
include/webui.h

This copies the Linux build to generate binaries for MacOS. Resolves #59

✨Add a build for MacOS

---

src/webui.c

The example without the fix:
With the fix:

Fix missing last characther bug

---

examples/C++/VS2019/serve_a_folder/my_webui_app/my_webui_app.cpp
examples/C++/VS2019/serve_a_folder/my_webui_app/webui.hpp
examples/C++/VS2022/serve_a_folder/my_webui_app/my_webui_app.cpp
examples/C++/VS2022/serve_a_folder/my_webui_app/webui.hpp
include/webui.hpp

Fix C++ examples

---

src/webui.c

#104 
Currently I can't download & make vivaldi-snapshot from AUR  to test, but this should work

Vivaldi-snapshot condition for Arch

---

.github/workflows/build.yml

<em>PR description will be updated</em>

ci: add release step

---

Makefile

Enquote paths in Makefile

---

src/webui.c

They ship three versions. The beta version the beta version is the medium paced version.

Inlcude `microsoft-edge-beta` in `webui_browser_exist` check

---

include/webui.h
src/webui.c

We have webui_set_multi_access(), but how to get the URL?

Add webui_get_url

---

examples/C/text-editor/ui/css/style.css

Fixes an issue where clicking on the icons in the text editor examples has no effect but it's required to click the area around the icon.

Fix clicking on icon in text-editor example

---

examples/C/text-editor/Makefile

Fix text editor debug build

---

.github/workflows/linux.yml
.github/workflows/macos.yml
Makefile
examples/C++/call_cpp_from_js/Makefile
examples/C++/call_js_from_cpp/Makefile
examples/C++/minimal/Makefile
examples/C++/serve_a_folder/Makefile
examples/C/call_c_from_js/Makefile
examples/C/call_js_from_c/Makefile
examples/C/minimal/Makefile
examples/C/serve_a_folder/Makefile
examples/C/text-editor/Makefile

Sample workflow on PR branch: https://github.com/ttytm/webui/actions/runs/6342191476
For now, the added releases are gcc compiled.
---
Edit:
broke mac arm, it falls back to x64 atm.

Support more architectures, add linux `aarch64` and `arm` releases

---

.pre-commit-config.yaml
src/webui.c

Adds a pre-commit git hook for clang format.

Add pre-commit config

---

build.zig

1. Solved the problem of failure to build dynamic libraries on Windows platform
2. But currently the dynamic link building example is not available under windows, see this issue:https://github.com/ziglang/zig/issues/15107

Simplify build files

---

src/civetweb/civetweb.c

Resolves <https://github.com/webui-dev/webui/issues/335>

Add MIME type for `.mjs`

---

build_12.zig

`installHeader` and `LazyPath` has changes, see these PR:
https://github.com/ziglang/zig/pull/19167
https://github.com/ziglang/zig/pull/19597
Please do not merge this PR for now because it is not completed yet and I need to wait for an important PR from upstream
https://github.com/ziglang/zig/pull/19597 to be merged before I can continue the implementation.

fix api changes of nightly zig `installHeader`

---

build.zig
build_13.zig

No changes for code logic, just adapt to zig `nightly`
Now, zig `0.12` has been released, zig `nightly` is `0.13`
And I need some test for this PR!

[Update]: update to zig nightly 0.13 support

---

build.zig

My apologies, in my previous PR I limited cache files to exclude examples when `webui` is retrieved as a dependency but did not accordingly update `webui`'s `build.zig` to avoid opening the non-existent `examples` folder.

Hotfix: Zig build attempts to open examples directory from dependency

---

build.zig

Continuation of #522 @AlbertShown

Support building `civetweb` in debug mode

---

build.zig

This should help close https://github.com/webui-dev/zig-webui/issues/72

Support webui debug logs
