- CMakeLists.txt
from
cmake_minimum_required(VERSION 3.15.0)
to
cmake_minimum_required(VERSION 3.13.4)
> تم تغير رقم اصدار cmake

- src/webui.c
This pr disables chrome's first-run dialog at new profile creation.
> Disable First Run Dialog

- src/webui.c
Fix Warning C6295 Ill-defined for-loop. Loop executes infinitely.
> Fix C6295 Ill-defined for-loop

- include/webui.hpp
`NULL` could be implicitly cast to `int(0)`, `nullptr` prevents this and has no downside.
Simple quality of life change, it has no downside and allows users to call the const-ed function even if it has a const instance.
Empty destructors and explicit default constructors prevent the compiler from automatically generating copy constructors, move constructors, and assign operators; since it makes the compiler think that the specific class has a special lifetime, this isn't the case for the `window` class, so removing the destructor results in its automatic generation and the automatic generation of the other functions. 
This prevents members from being initialized by default and then copied.
See #103
This prevents the ODR rule violation
_Note: This is not function inlining that prevents …
> Adherence to noninvasive C++ best practices

- src/webui.c
Fix for the issue #104 
Added condition to check `vivaldi-stable` on Arch based distros additinally to `vivaldi`
Tested on Arch and Ubuntu.
> vivaldi fix for Arch

- examples/C++/call_cpp_from_js/main.cpp
- examples/C++/call_js_from_cpp/main.cpp
- examples/C++/serve_a_folder/main.cpp
- include/webui.hpp
- Eliminate the need for a conversion function between webui::event and webui_event_t.
- Incapsulate the event handling capabilities in a static class.
- Break the circular dependency between types defined in the C++ header.
This PR is only intended to be a code restructuring, and doesn't mean to change how the header achieves the functionality it provides.
- These changes slightly change the API, so the example needs to be updated (this PR encapsulates the event struct inside the window class, so to declare an event instance you now need `webui::window::event` instead of `webui::event`).
- This PR is marked as draft because I expect a discussion on these changes, if the changes are well received, I will update the examples.
- These changes have already been tested on Linux using firefox …
> C++ header restructured.

- examples/C++/VS2019/serve_a_folder/my_webui_app/webui.hpp
- examples/C++/VS2022/serve_a_folder/my_webui_app/webui.hpp
- examples/C++/call_js_from_cpp/main.cpp
- examples/C++/serve_a_folder/main.cpp
- include/webui.hpp
As the title says, this is the final PR for the C++ header reorganization; now the C++ API should be in a good place, being as fast as the C with OOP in mind.
Main changes in this PR:
- Now event is a class with it's own methods (see [this](https://github.com/webui-dev/webui/pull/106#issuecomment-1563526571))
- Some examples still used `e->window` instead of `e->get_window()` 
All examples are tested and confirmed to work on Linux with Firefox as browser and clang or gcc as compiler.
> C++ header reorganization completed.

- build/linux_build.sh
- build/macos_build.sh
- build/windows_build.bat
Add compression and output files with extensions which indicate the file type more accurately.
Fixes #120
> Rename output to `*.tar.gz`

- src/webui.c
- src/webui_core.h
Send `webui_html_*` erros via `mg_send_http_*`  use the wrong mime type (text/plain) and so badly display the error.
Civetweb only allow serving error page as text/plain so need I added a new webui internal function to serve text/html error pages.
> fix: html error pages displayed as plain text

- src/webui.c
- src/webui_core.h
Since webui script tag is injected after html, any declared js file in the html payload is parsed before the API.
Unless set it "defer" it is executed before the API and cause an error.
I change the html structure order to force js bridge to execute before any user content.
Since bridge is loaded in html head I fix possibly undefined listener that crash the app.
Moreover, since webui.c allow to load js via 2 way (embbeded and via a get url) I choose to the the url way to avoid memory management for future improve and simplify the code (and js was truncated after the changes if I keep string concat approach). In bonus it allow to debug js via the source panel in dev console.
To force top loading I used the auto correct behaviour of html and then construct bad html to load js bridge before …
> fix: :bug: webui js API is undefined

- src/webui.c
Currently, the arguments for all chromium-based browsers are the same, and are hardcoded into each start function. This adds a function that autofills the CLI arguments.
```
static int _webui_get_browser_args(_webui_window_t* win, size_t browser, char *buffer, size_t max);
```
The browser type is passed through in browser - sometimes win->current_browser is set as DefaultBrowser, and the start function is trying all CLI arguments to see which one runs.
Some improvements that could be made:
- `_webui_get_browser_args` only fills in *flags*, but it might be better for it to build the entire CLI command. This could eliminate
```
char full[1024] = {0};
sprintf(full, "%s%s%s", win->browser_path, arg, address);
```
In each function
- The current code doesn't use `max` (the old code didn't …
> Refactor hardcoded browser CLI arguments

- .github/workflows/build.yml
This PR reworks the build workflow to fix and extend it.
The main feature this results in is a CI of deployed build artifacts.
Example: https://github.com/tobealive/webui/actions/runs/5626014645
While working on this feature, the current build workflow revealed itself as a bit foolish. Up until now there was no testing of windows with MSVC. This can either be seen by listing the directory contents or by uploading the build artifacts after the nmake command was run - both would result in an empty output. So this issue had to be fixed within the frame of this PR. All in all I tried to add the best practices and performance optimizations that I knew of.
The changes are the major part of #134. I will build upon them in the coming days to use the produced build artifacts in a workflow for …
> ci: rework build workflow, deploy artifacts

- src/webui.c
After compiling lib with these two flags removed, I have noticed significant improvement in performance of my app.
I understand those two flags are opposite to each other, first one disables GPU rendering and second one disables CPU rendering, my understanding might be wrong, but I don't see a reason to have both of them passed together.
> allow faster rendering

- .github/workflows/build.yml
Either it was a transitory bug with the Cachefile action or it is due to changing the shell for windows.
This PR should fix it. I make sure the change is compatible with the new Makefile in the root directory before marking it as ready.
> Fix CI cache restore for Windows

- README.md
- Updates formatting for the table of supported web browsers
current: https://github.com/webui-dev/webui#supported-web-browsers
suggested: https://github.com/ttytm/webui/tree/docs/format#supported-web-browsers
- Removes first indent level whitespace for a list to e.g. match the formatting for the `Feature section
What do you think of adding a table of contents on top of the Readme for quick navigation? Kind of like here: https://github.com/ttytm/wthrr-the-weathercrab#-wthrr-the-weathercrab
Just above the `Features` section.
> Update table format for supported web browsers

- README.md
This suggestion is an attempt to make the readme even cleaner for a polished first impression.
- The block quotes on top of the readme are currently repetitive. So the first point is merged into a single initial statement.
- We are currently writing documentation is moved into the documentation section as GitHub Note highlight.
To save you a few sec navigating to the rendered preview:
current: https://github.com/webui-dev/webui
suggestion: https://github.com/ttytm/webui/tree/docs/update-note
Let me know what you think.
> Cleanup quotes

- .github/workflows/build.yml
- Makefile
I encounter the same issue with the dist dir creation in the Makefile when using the library in the V wrapper CI. That the current command to conditionally create a directory on Windows is not working reliable, looks like a version related issue.
The current command `@-$(shell if not exist $(BUILD_DIR) mkdir -p "$(BUILD_DIR)" >nul 2>&1)`
wanted to omit the ignored error message `mingw32-make: [Makefile:77: --setup] Error 1 (ignored)` if the dist directory already existed. With the newly used command this is also possible and it has better compatibility.
> Fix `mkdir dist` in build step on windows

- Makefile
Fixes the file cleanup for Windows GCC CI builds and remaining file residues in the archives.
The shell switches to bash, despite calling the make command from the default powershell. When we unignore all errors we then get `/usr/bin/bash: line 1: del: command not found`.
Includes a mini revert of a mistake in the last commit. The path should not be enquoted on declaration as we still add more segments to it in other places. Sorry about that.
> Fix file deletion in Windows GCC CI build

- include/webui.h
Adds some small updates to the comments in the header file. 
It makes usage of trailing dots and backtick quotation uniform and refines spelling.
> Refine API comments

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
Testing the release workflow. I've run into the possibility to encounter permission errors when running the build script for the client. This change makes sure permissions are set.
> Prevent bridge build permission error

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
Adds building of the debug version to the CI workflow.
That way users could always download pre-built static for the latest commit from the github actions artifacts. (Related https://github.com/webui-dev/pascal-webui/issues/3#issuecomment-1699829791)
Also, if I recall it right, after moving to the single Makefile approach, you had to fix an issue with the debug build that might have been covered when `make debug` would be part of CI.
E.g.: https://github.com/ttytm/webui/actions/runs/6040804140
When creating a tag release, still only the release version would be uploaded to github releases.
> Include debug builds in CI

- examples/C++/call_cpp_from_js/Windows/MSVC/Makefile
- examples/C++/call_cpp_from_js/macOS/Clang/Makefile
- examples/C++/call_js_from_cpp/Windows/MSVC/Makefile
- examples/C++/call_js_from_cpp/macOS/Clang/Makefile
- examples/C++/minimal/Windows/MSVC/Makefile
- examples/C++/minimal/macOS/Clang/Makefile
- examples/C++/serve_a_folder/Windows/MSVC/Makefile
- examples/C++/serve_a_folder/macOS/Clang/Makefile
- examples/C/call_js_from_c/Windows/MSVC/Makefile
- examples/C/call_js_from_c/macOS/Clang/Makefile
- examples/C/minimal/Windows/MSVC/Makefile
- examples/C/minimal/macOS/Clang/Makefile
- examples/C/serve_a_folder/Windows/MSVC/Makefile
- examples/C/serve_a_folder/macOS/Clang/Makefile
\+ make uniform usage of comments in macos Makefiles - the current version with the leading spaces prints the comments.
> Remove remaining `@cd "$(_LIB)" && $(MAKE)` residues in examples

- Makefile
- Makefile.nmake
This PR:
- makes use of the `git rev-parse --show-topleve` shell command (same as it's done in brdige/build.sh) in our regular `Makefile` to get the Makefile directory.
- utilizes `MAKEDIR` which comes with nmake in `Makefile.nmake` it to get the Makefile dir instead of fixing it to `./`. 
also makes `/` usage in paths consistent.
> Improve directory independency of Makefile Dir variables

- README.md
This includes a minor cosmetic change.
It updates the "wide" images in the readme to re-created versions. The main goal was to make all wide images fill a readmes max content (1012px is max at GH afaik). 
For the other changes, I hoped the updated cppcon snapshot is in initially a bit simpler and more interesting and that the Diagram image transmits the point of how easy it is to create an application with full OS API access (it's obvious when thinking about it, now it's in the image as well). The Diagram also won't use a shadow anymore to keep things uniform.
Quick link to rendered preview: https://github.com/ttytm/webui/tree/readme/update-images
The current state is also good, and those are things where preferences might differ, so please tell if the changes are a +.
> Update images with wide widths to fill content

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- Makefile
- Makefile.nmake
- examples/C++/call_cpp_from_js/Makefile
- examples/C++/call_cpp_from_js/Makefile.nmake
- examples/C++/call_js_from_cpp/Makefile
- examples/C++/call_js_from_cpp/Makefile.nmake
- examples/C++/minimal/Makefile
- examples/C++/minimal/Makefile.nmake
- examples/C++/serve_a_folder/Makefile
- examples/C++/serve_a_folder/Makefile.nmake
- examples/C/call_c_from_js/Makefile
- examples/C/call_c_from_js/Makefile.nmake
- examples/C/call_js_from_c/Makefile
- examples/C/call_js_from_c/Makefile.nmake
- examples/C/minimal/Makefile
- examples/C/minimal/Makefile.nmake
- examples/C/serve_a_folder/Makefile
- examples/C/serve_a_folder/Makefile.nmake
Using a distinct file for debug builds would simplify some things imho. There are a bunch of cases where it makes sense to have both files side by side.
If you also see value in this, I'd finish it here.
> Improve debug build target usage

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
Implement nightly releases that are automatically updated when changes to the main branch are made.
This change should work very well as it is, but there are always improvements to make.
E.g. possible future improvements:
- Making releases could be split into it's own `release` workflow and file. This would require some re-organisation, since artifacts would need to be downloaded to make them accessible for a separate job and the release preparation would need to be done there, after downloading.
- What triggers a nightly release could be narrowed down further to changes that are decided to be relevant (the separate workflow mentioned above would be supplementary for this).
> Implement nightly releases

- README.md
- examples/C/README.md
- examples/C/text-editor/README.md
A change suggestion based on recent conversations and updates.
The statement next to the text-editor example `The final executable is portable and has less than _1 MB_ in size (_+html and css files_).` was recently removed at certain places. Now, the relevant parts are updated to `[...] is a lightweight and portable example written in C using WebUI as the GUI library.`
Hoping to prevent misconceptions about portability of the executable and size of the editor, while keeping the essence of the statement.
The screenshot in the text-editor examples README was update to the Windows screenshot used on the website. 
https://github.com/ttytm/webui/tree/examples/update-text-editor-screenshot/examples/C/text-editor
If the screenshot in the main README should also be updated or something should be …
> Update text editor example docs

- src/civetweb/civetweb.c
An unintended changed slipped through in https://github.com/webui-dev/webui/pull/168/files
It probably did not cause any issues, as the libs are usually also accessible by this name. But like this it's a duplicate condition in the civetweb.c code, and should be reverted.
> Revert unintended search and replace changes

- .github/workflows/linux.yml
Currently, it falls back to default GCC.
> Fix clang build in Linux CI

- src/webui.c
"--disable-translate" doesnt work since few years. For Chrome to offer a translation just refresh the WebUI with Ctrl+R (maybe several times). The text in the browser must be in a language different than yours of course.
"--disable-features=Translate" fixes it, but I would keep "--disable-translate" too.
> Fix disabling translate feature on Chromium based browsers

- examples/C/text-editor/text-editor.c
- examples/C/text-editor/ui/css/style.css
- examples/C/text-editor/ui/index.html
- examples/C/text-editor/ui/js/ui.js
Two improvements are made. Currently, saving a file is only enabled when a file is opened. This is accompanied by that it is not possible to save text that is simply typed into the editor - without a file having been opened before.
The PR:
- Enables the save button when a change is made in the editor. It will also be disabled again after saving a file until the next change is made.
- Allows saving text entered in the editor when no file has been opened and sets the file data (doctitle and language) after saving.
- Makes some minor refactors.
> Improve text editor example

- src/webui.c
Fix a typo at `webui.c:4511`
`browser` here is ridiculous since we may assert `browser == AnyBrowser` in this if-branch.
> Fix a typo at `webui.c:4511`

- .github/workflows/linux.yml
`aarch64` -> `arm64` for linux releases
> Use uniform arm architecture name for release archives

- .github/workflows/macos.yml
Reverts the recent PR, that had no effect on the outcome.
Creates the compressed archive before uploading as an attempt to solve an issue for macos-x64 where the uploaded release archive seems to get corrupted. In case the upload action has an effect on the later archived files this should prevent it.
> Create mac archive before uploading

- build.zig
Optimizing the build process, we can now use zig to build all C examples
Like this:
```sh
❯ zig build --help
Usage: /usr/lib/zig/zig build [steps] [options]
Steps:
install (default)            Copy build artifacts to prefix path
uninstall                    Remove build artifacts from prefix path
build_all                    build all examples
run_call_js_from_c           run exmaple call_js_from_c
run_public_network_access    run exmaple public_network_access
run_call_c_from_js           run exmaple call_c_from_js
run_text-editor              run exmaple text-editor
run_custom_web_server        run exmaple custom_web_server
run_serve_a_folder           run exmaple serve_a_folder
run_minimal                  run exmaple minimal
```
> Optimizing the build process

- bridge/build.ps1
Previously we didn't set error action or strict mode, meaning we would inherit what the user had as their default.  If set to stop it would break.  Instead of just setting it to silent  I used stop mode for most.  Also enabled strict mode.
> Use strict mode for powershell bridge script

- build.zig
This is just a little fix for this PR: https://github.com/webui-dev/webui/pull/353
Since zig's build system will completely try to build the dependence `build.zig`, a detection is added and it will be returned directly when versions `0.12` and later appear.
> [Zig build]: little fix

- .github/workflows/linux.yml
As discussed in [#321](https://github.com/webui-dev/webui/issues/321), the people who run WebUI on Ubuntu 20.04 or lower get the error of version `GLIBC_2.33' not found`  since they have `glibc 2.31`(for the case of Ubuntu 20.04) or lower. Currently, a workaround has to be used as explained [here](https://github.com/webui-dev/webui/issues/321#issuecomment-2075075790). To solve this problem, Ubuntu version in the linux workflow should be changed to `ubuntu-18.04` as proposed [here](https://github.com/webui-dev/webui/issues/321#issuecomment-1914961370).
> change ubuntu version in linux workflow to support legacy glib

- build.zig
Informs about the reason for an unsuccessful build when using the latest zig version.
The exit code 1 makes the build better verifiable in regular and automated scenarios.
> Don't return silently when zig build is not possible

- build.zig
It’s really handy to have the possibility to build with Zig; it provides everything so fast. I’m just getting into using it more now. Thanks for adding it @jinzhongjia .
The changes simplify building the examples. It removes two nesting levels by handling the "unhappy-path" early.
> Simplify building examples with Zig

- .github/workflows/ci.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- .github/workflows/zig.yml
- Makes a maintenance update to the workflows, resolving deprecation warnings.
- Adds a concurrency group setting to prevent omit stacking unnecessary runs.
- Adds a workflow to test building the lib and examples with zig.
> Update workflows, add zig build

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
The PR should help to detect errors and ensure that users can continue to build examples.
Some extracted examples from a test run on the PR fork (for a full overview, please check the CI jobs below the PR):
|macOS|Windows|
|-|-|
|![Screenshot_20240528_180933](https://github.com/webui-dev/webui/assets/34311583/73cd39da-c50e-44c4-afed-25bba4d38ea5)|![Screenshot_20240528_181017](https://github.com/webui-dev/webui/assets/34311583/8b31ec04-eb2b-4395-8415-077c4c4bcdb2)|
> Extend test coverage, add CI steps to build C examples with make

- .github/workflows/zig.yml
- build.zig
Adds the ability to compile WebUI and its examples with Zig 0.12.0 ~~and the Zig development version~~ _gonna keep it down to Zig release versions for now to avoid having additional trouble wit breaking changes over at Zig_.
> Support compiling with zig 0.12.0 

- include/webui.h
- src/webui.c
The PR is mainly about making signatures more expressive.
- ~~Updating the return type of `webui_get_best_browser` to `webui_browser` instead of size_t.~~
- Updating enum names to a singular form. Since an enum represents _one_ constant with the same name, it is a closer description of the value that should be passed/received. For example, `config`/`browser` instead of `configs`/`browsers`.
While the C enum names are used in the public function signatures to indicate types, there is no direct "outside" usage of the actual C enum names. So, afaik, this change shouldn't cause any breaks for one of the wrappers and should just improve expressiveness.
> Use singular form for enum names

- README.md
in alphabetical order after the webui-dev repositories.
> README: add Common Lisp wrapper

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
The PR would add GitHub issue templates.
I've created some github form templates customized for the webui repositories.
- Rationale:
Many reported issues are platform dependent, and the same questions are often asked after an issue is opened and require a response before work can be done to resolve it. The templates can guide a user to provide all the necessary information immediately so that issues can be resolved as quickly as possible.
If you want to test it, I've pushed it to the main fork branch to make it testable: https://github.com/ttytm/webui/issues. Start the issue creation / or finish it, I will delete the issues afterwards.
Suggestions are welcome.
> Add issue templates

- src/webui.c
I removed platform-dependent CSS and used Firefox default titlebar support.
- Since Titlebar is handled by platform, titlebar is looking more consistent with system.
- Since removed platform-dependent CSS, should be fixed issues (like #85) and code should be more future-proof.
- Untested on Windows and MacOS yet. _If you test the PR on the platforms, can you share your test results._
TODO:
Tested on:
> Remove platform-dependent CSS and use browser titlebar on Firefox

- src/civetweb/README.md
Adds a readme to civetweb as a reminder about currently required modifications to ensure full direct interoperability for wrappers:
Rendered preview:
>   ```diff
>   + #ifndef NDEBUG
>   #define malloc DO_NOT_USE_THIS_FUNCTION__USE_mg_malloc
>   #define calloc DO_NOT_USE_THIS_FUNCTION__USE_mg_calloc
>   #define realloc DO_NOT_USE_THIS_FUNCTION__USE_mg_realloc
>   #define free DO_NOT_USE_THIS_FUNCTION__USE_mg_free
>   #define snprintf DO_NOT_USE_THIS_FUNCTION__USE_mg_snprintf
>   + #endif
>   ```
> Add readme about required modifications to civetweb

- include/webui.h
The PR should resolved the last changed required to satisfy the go compiler when directly using WebUI as a submodule.
It will allow for: https://github.com/webui-dev/go-webui/pull/35
On linux, dirent is always included:
https://github.com/webui-dev/webui/blob/561c0449244f60b7bfdb2b877b17242c238f12e7/include/webui.h#L75-L76
> Fix conflict with including dirent

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
I simplified the release condition too much with one of the recent updates. We would encounter an issue on the next tag release (I already did in another project after making a similar change).
While creating a tag is a push event, the ref_name is not the branch name like main but the tag's name. So, the condition would be false when it shouldn't be.
> Fix condition for release steps when pushing tags

- src/civetweb/README.md
Both pull request that addressed the conflicts with civetweb were merged. The workarounds are now obsolete and included when updating to latest civetweb.
Related civetweb pulls that contain the changes: \#1261 \#1266
> Remove docs for workarounds for resolved thrid-party conflicts

- build.zig
The `build.zig` linker flags setting caused issues with linking `civetweb`, notably redefinition of `MUST_IMPLEMENT_CLOCK_GETTIME` macro and a warning for using the `__DATE__` macro (which turns into an error with default Zig compiler flags). This occurred when attempting to build `webui` with Zig in any release mode on Windows (potentially other OSes as well, but untested).
This patch addresses these issues and allows for building on release modes in at least Windows and Linux systems.
> Fix release mode building with Zig

- .github/workflows/zig.yml
- build.zig
- build.zig.zon
Clean up and improvements to current Zig build process. Notably:
1. Specify paths in `build.zig.zon` to limit files stored in cache when `webui` is fetched as a dependency
2. Set `verbose` option to be an enum of levels, so that more specific build information can be emitted 
3. Fix bug where prior `verbose` option printed `Done.` immediately before build process completed
4. General cleanup of linker flags and file paths to adhere to Zig best practices
> Zig build improvements

- src/webui.c
- mismatch error,  use strdup() alloc memory, but use _webui_free_mem() to free
- double free error,  _webui_get_full_path() already free 'file' internal, but free again when use
- can't free ws library memory data which not alloced by webui
- can't free const memory
> Fix memory error

- include/webui.h
This PR will fix tcc compile fail error:
```sh
error: declaration for parameter 'webui_new_window' but no such parameter
```
> fix linux tcc compile fail

- src/webui.c
Make sure calling `web_malloc(4096)` will alloc 4096 bytes indeed, not 8192 bytes.
> make sure 4096 bytes not alloc 8192 bytes

- .github/workflows/zig.yml
- build.zig
- build.zig.zon
> Drop Zig 0.11.0 support

- build.zig
- introduce enable-webui-log option to control WebUI log output
- update addLinkerFlags to accept enable_webui_log parameter
- conditionally define WEBUI_LOG macro based on debug and enable_webui_log
> feat(build): add enable-webui-log build option
